In [1]:
from IPython.display import clear_output
import openml # openML
import pandas as pd
import numpy as np
from os import listdir # get dir list
from os.path import isfile, join # get dir list
import random
from pymfe.mfe import MFE



/home/lpfgarcia/pedropio/NoiseSelection/NoiseEnvPy/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [5]:
openml_list = openml.datasets.list_datasets()  # returns a dict

# Show a nice table with some key data properties
datalist = pd.DataFrame.from_dict(openml_list, orient="index")

idList = datalist[(datalist.NumberOfClasses ==2) &
 (datalist.NumberOfFeatures >=3) &
 (datalist.NumberOfFeatures <= 100) &
 (datalist.NumberOfInstances >= 50) &
 (datalist.NumberOfInstances <= 20000) &
 (datalist.NumberOfMissingValues ==0)]['did'].values

idList.astype(int)
idList = idList.tolist()


data = openml.datasets.get_datasets(idList, download_data = True)

In [11]:
className = df.columns[len(df.columns)-1]
len(df[className].unique())

2

In [10]:
df = data[0].get_data(dataset_format ='dataframe')[0]
numberColumns = len(df.columns))
df.columns = list([f'X_{i}' for i in range(numberColumns)])
df 


X_0 X_1 X_2 X_3 X_4 X_5 X_6 X_7 X_8 X_9  ... X_27 X_28 X_29 X_30 X_31  \
0      f   f   f   f   f   f   f   f   f   f  ...    f    f    f    f    f   
1      f   f   f   f   t   f   f   f   f   f  ...    f    f    f    f    f   
2      f   f   f   f   t   f   t   f   f   f  ...    f    f    f    f    f   
3      f   f   f   f   f   f   f   f   t   f  ...    f    f    f    f    f   
4      f   f   f   f   f   f   f   f   f   f  ...    f    f    f    f    f   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...   
3191   t   f   f   f   f   f   t   f   f   f  ...    f    t    f    f    t   
3192   t   f   f   f   f   f   t   f   f   f  ...    f    t    f    f    t   
3193   t   f   f   f   f   f   t   f   f   f  ...    f    t    f    f    t   
3194   t   f   t   f   f   f   t   f   f   f  ...    f    t    f    f    t   
3195   t   f   t   f   f   f   t   f   f   f  ...    f    t    f    f    t   

     X_32 X_33 X_34 X_35   X_36  
0       f    t    t    n    won  
1       f    t    t    n    won  
2       f    t    t    n    won  
3       f    t    t    n    won  
4       f    t    t    n    won  
...   ...  ...  ...  ...    ...  
3191    f    t    f    n  nowin  
3192    f    t    f    n  nowin  
3193    f    t    f    n  nowin  
3194    f    f    f    n  nowin  
3195    f    f    f    n  nowin  

[3196 rows x 37 columns]

In [19]:
# len(getFolderFilesList('Datasets'))
len(error)

64

In [12]:
ok = 0
dataNames = []
error = []
tooMuchColumns = 0
tooManyClass = 0
for j in data:
    try:
        df1 = j.get_data(dataset_format ='dataframe')
        df = df1[0]
        if j.name in dataNames:
            continue
        dataNames.append(j.name)
        for i in df.columns:
            # print(df[i].dtype)
            if (df[i].dtype == object or df[i].dtype == 'category' or df[i].dtype == 'string'):
                if(len(df[i].unique()) <= 2):
                    df[i] = (df[i] == df[i].iloc[0])*1
        className = df.columns[len(df.columns)-1]
        classValues = df[className]
        
        if (len(df[className].unique()) != 2):
            tooManyClass +=1
            continue        
        
        df = df.drop(className, axis=1)
        df = pd.get_dummies(df)

        numberColumns = len(df.columns)
        if (numberColumns > 200):
            tooMuchColumns+=1
            continue

        df.columns = list([f'X_{i}' for i in range(numberColumns)])

        df['class'] = classValues
        # print(f'NoiseSelection/Datasets/{str(j.id)}_{j.name}.csv.zip')
        df.to_csv(f'Datasets/{str(j.id)}_{j.name}.csv.zip', index=False)
        ok+=1
        
    except:
        error.append(j.name)

In [37]:
df = pd.read_csv('/home/lpfgarcia/pedropio/NoiseSelection/Datasets/3_kr-vs-kp.csv.zip')
addNoiseToDf(df, 'class', 20)
# df

X_0  X_1  X_2  X_3  X_4  X_5  X_6  X_7  X_8  X_9  ...  X_29  X_30  X_31  \
0       1    1    1    1    1    1    1    1    1    1  ...     1     1     1   
1       1    1    1    1    0    1    1    1    1    1  ...     1     1     1   
2       1    1    1    1    0    1    0    1    1    1  ...     1     1     1   
3       1    1    1    1    1    1    1    1    0    1  ...     1     1     1   
4       1    1    1    1    1    1    1    1    1    1  ...     1     1     1   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   
3191    0    1    1    1    1    1    0    1    1    1  ...     1     0     1   
3192    0    1    1    1    1    1    0    1    1    1  ...     1     0     1   
3193    0    1    1    1    1    1    0    1    1    1  ...     1     0     1   
3194    0    1    0    1    1    1    0    1    1    1  ...     1     0     1   
3195    0    1    0    1    1    1    0    1    1    1  ...     1     0     1   

      X_32  X_33  X_34  X_35  X_36  X_37  class  
0        1     1     1     0     1     0      1  
1        1     1     1     0     1     0      1  
2        1     1     1     0     1     0      1  
3        1     1     1     0     1     0      1  
4        1     1     1     0     1     0      0  
...    ...   ...   ...   ...   ...   ...    ...  
3191     1     0     1     1     0     0      0  
3192     1     0     1     1     0     0      0  
3193     1     0     1     0     1     0      0  
3194     0     0     1     1     0     0      0  
3195     0     0     1     0     1     0      0  

[3196 rows x 39 columns]

In [5]:

def getFolderFilesList(path):
    return [filename for filename in listdir(path) if isfile(join(path, filename))]

def addNoiseToDf(df, atribute, percent):
    df_copy = df.copy()
    labels = df[atribute].unique()
    sizeDf = len(df.index)
    quantityOfNoise = int((sizeDf*(percent)/100))
    listOfChangedIndex = random.sample(range(0, sizeDf - 1), quantityOfNoise)
    for index in listOfChangedIndex:
        newLabel = labels[1] if df[atribute][index] == labels[0] else labels[0]
        df_copy[atribute][index] = newLabel
    return df_copy

In [38]:
listOfFiles = getFolderFilesList('Datasets')
for file in listOfFiles:
    df = pd.read_csv(f'Datasets/{file}')
    for i in range(10):
        df5 = addNoiseToDf(df, 'class', 5)
        df10 = addNoiseToDf(df, 'class', 10)
        df20 = addNoiseToDf(df, 'class', 20)
        # df40 = addNoiseToDf(df, 'class', 40)
        dfName = file.split('.')[0]
        df5.to_csv(f'NoisyDatasets/{dfName}_5_{str(i)}.csv.gz', index=False)
        df10.to_csv(f'NoisyDatasets/{dfName}_10_{str(i)}.csv.gz', index=False)
        df20.to_csv(f'NoisyDatasets/{dfName}_20_{str(i)}.csv.gz', index=False)
        # df40.to_csv(f'NoisyDatasets/{dfName}_40_{str(i)}.csv.gz', index=False)


/tmp/ipykernel_3834027/1289401310.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_copy[atribute][index] = newLabel
/tmp/ipykernel_3834027/1289401310.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_copy[atribute][index] = newLabel
/tmp/ipykernel_3834027/1289401310.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_copy[atribute][index] = newLabel
/tmp/ipykernel_3834027/1289401310.py:13: SettingWithCopyWarning: 
A va

In [4]:
len(getFolderFilesList('/home/lpfgarcia/pedropio/NoiseSelection/NoisyDatasetsAfterFilters/HARF'))

NameError: name 'getFolderFilesList' is not defined

In [3]:
df = pd.read_csv('/home/lpfgarcia/pedropio/NoiseSelection/Datasets/3_kr-vs-kp.csv.zip')

#testing pyMFE library
X, y = df.drop('class', axis=1), df['class']
listOfMfeGroups = ["general", "statistical", "info-theory", "model-based", "landmarking"]
# listOfMfeGroups = ["general"]
mfe = MFE(groups=listOfMfeGroups)
mfe.fit(X.values, y.values)
ft = mfe.extract()
print(ft)
pd.DataFrame(columns=ft[0], data = [ft[1]])

/home/lpfgarcia/pedropio/NoiseSelection/NoiseEnvPy/lib/python3.8/site-packages/pymfe/_internal.py:1566: UserWarning: It is not possible make equal discretization
  warnings.warn("It is not possible make equal discretization")
/home/lpfgarcia/pedropio/NoiseSelection/NoiseEnvPy/lib/python3.8/site-packages/pymfe/_internal.py:731: RuntimeWarning: Can't summarize feature 'can_cor' with summary 'sd'. Will set it as 'np.nan'.
  warnings.warn(
/home/lpfgarcia/pedropio/NoiseSelection/NoiseEnvPy/lib/python3.8/site-packages/pymfe/_internal.py:606: RuntimeWarning: Can't extract feature 'g_mean'.
 Exception message: ZeroDivisionError('division by zero').
 Will set it as 'np.nan' for all summary functions.
  warnings.warn(
/home/lpfgarcia/pedropio/NoiseSelection/NoiseEnvPy/lib/python3.8/site-packages/pymfe/_internal.py:731: RuntimeWarning: Can't summarize feature 'g_mean' with summary 'sd'. Will set it as 'np.nan'.
  warnings.warn(
/home/lpfgarcia/pedropio/NoiseSelection/NoiseEnvPy/lib/python3.8/sit

(['attr_conc.mean', 'attr_conc.sd', 'attr_ent.mean', 'attr_ent.sd', 'attr_to_inst', 'best_node.mean', 'best_node.sd', 'can_cor.mean', 'can_cor.sd', 'cat_to_num', 'class_conc.mean', 'class_conc.sd', 'class_ent', 'cor.mean', 'cor.sd', 'cov.mean', 'cov.sd', 'eigenvalues.mean', 'eigenvalues.sd', 'elite_nn.mean', 'elite_nn.sd', 'eq_num_attr', 'freq_class.mean', 'freq_class.sd', 'g_mean.mean', 'g_mean.sd', 'gravity', 'h_mean.mean', 'h_mean.sd', 'inst_to_attr', 'iq_range.mean', 'iq_range.sd', 'joint_ent.mean', 'joint_ent.sd', 'kurtosis.mean', 'kurtosis.sd', 'leaves', 'leaves_branch.mean', 'leaves_branch.sd', 'leaves_corrob.mean', 'leaves_corrob.sd', 'leaves_homo.mean', 'leaves_homo.sd', 'leaves_per_class.mean', 'leaves_per_class.sd', 'lh_trace', 'linear_discr.mean', 'linear_discr.sd', 'mad.mean', 'mad.sd', 'max.mean', 'max.sd', 'mean.mean', 'mean.sd', 'median.mean', 'median.sd', 'min.mean', 'min.sd', 'mut_inf.mean', 'mut_inf.sd', 'naive_bayes.mean', 'naive_bayes.sd', 'nodes', 'nodes_per_attr'

attr_conc.mean  attr_conc.sd  attr_ent.mean  attr_ent.sd  attr_to_inst  \
0        0.116539      0.187649       0.512743     0.403761       0.01189   

   best_node.mean  best_node.sd  can_cor.mean  cat_to_num  class_conc.mean  \
0        0.489635      0.127226      0.799823         0.0         0.190862   

   ...  tree_imbalance.sd  tree_shape.mean  tree_shape.sd  var.mean    var.sd  \
0  ...           0.092671         0.053968       0.095258  0.129471  0.085615   

   var_importance.mean  var_importance.sd  w_lambda  worst_node.mean  \
0             0.026316           0.063374  0.360284         0.536942   

   worst_node.sd  
0        0.04766  

[1 rows x 106 columns]

In [13]:
# extracts meta-features from clear datasets (without noise)
datasetsFilesNames = getFolderFilesList("NoisyDatasets")
listOfMfeGroups = ["general", "statistical", "info-theory", "model-based", "landmarking"]
data = pd.DataFrame()
count = 0
for dataset in datasetsFilesNames:
    df =  pd.read_csv("NoisyDatasets/" + dataset)
    mfe = MFE(groups=listOfMfeGroups, num_cv_folds= 5)
    X, y = df.drop('class', axis=1), df['class']
    mfe.fit(X.values, y.values)
    ft = mfe.extract()
    df_MFE = pd.DataFrame(columns=ft[0], data = [ft[1]])
    df_MFE["Dataset"] = dataset
    data = data.append(df_MFE)
    clear_output(wait=True)
    count +=1
    print ("exec " + str(count) + " / " + str(len(datasetsFilesNames)))

# data.dropna(axis=1)
data.to_csv("meta_features.csv",index=False)
data.dropna(axis=1).to_csv("meta_features_dropna.csv",index=False)

exec 10740 / 10740


In [15]:
data.dropna(axis=1)

attr_conc.mean  attr_conc.sd  attr_ent.mean   attr_ent.sd  attr_to_inst  \
0         0.322348      0.192551       2.638256  9.806912e-01      0.009957   
0         0.019834      0.057694       0.473077  9.098127e-01      0.235178   
0         0.008881      0.016986       1.055806  1.294135e+00      0.001728   
0         0.047483      0.137779       0.428992  4.205296e-01      0.551546   
0         0.302150      0.235341       2.309998  2.037383e-02      0.022901   
..             ...           ...            ...           ...           ...   
0         0.011608      0.002791       2.807320  5.747455e-06      0.100000   
0         0.038187      0.113721       0.723376  1.188980e-01      0.113772   
0         0.039173      0.064241       3.999987  1.382677e-05      0.001033   
0         0.012116      0.003220       2.807320  5.747455e-06      0.100000   
0         0.036504      0.055677       2.807320  4.681111e-16      0.020000   

    best_node.mean  best_node.sd  can_cor.mean  cat_to_num  class_conc.mean  \
0         0.807966      0.000204      0.400945         0.0         0.017971   
0         0.642225      0.114714      0.626243         0.0         0.011707   
0         0.762115      0.258361      0.532404         0.0         0.007431   
0         0.670175      0.060643      0.766494         0.0         0.049472   
0         0.840456      0.239731      0.763149         0.0         0.142263   
..             ...           ...           ...         ...              ...   
0         0.706000      0.045607      0.459857         0.0         0.003948   
0         0.892513      0.044132      0.785176         0.0         0.055724   
0         0.856582      0.000396      0.218460         0.0         0.000692   
0         0.614000      0.037815      0.359718         0.0         0.002673   
0         0.586000      0.091542      0.268250         0.0         0.006275   

    ...  tree_shape.mean  tree_shape.sd      var.mean        var.sd  \
0   ...         0.018328       0.039060  1.454982e+07  6.639671e+07   
0   ...         0.052013       0.070812  1.651275e+04  1.745700e+05   
0   ...         0.015451       0.035950  1.402869e+01  3.660596e+01   
0   ...         0.086797       0.113816  4.412514e+04  4.556090e+05   
0   ...         0.234375       0.092702  4.848672e+02  8.280360e+02   
..  ...              ...            ...           ...           ...   
0   ...         0.086830       0.086308  1.000000e+00  2.358762e-08   
0   ...         0.127131       0.111086  1.625842e-01  3.628665e-02   
0   ...         0.009012       0.030352  6.532042e+03  1.022981e+04   
0   ...         0.073771       0.082806  1.000000e+00  2.358762e-08   
0   ...         0.053340       0.061725  1.000000e+00  2.528778e-08   

    var_importance.mean  var_importance.sd  w_lambda  worst_node.mean  \
0              0.047619           0.035245  0.839243         0.807966   
0              0.008403           0.027135  0.607820         0.513842   
0              0.142857           0.354473  0.716546         0.706318   
0              0.009346           0.021198  0.412487         0.592848   
0              0.333333           0.471708  0.417603         0.847863   
..                  ...                ...       ...              ...   
0              0.020000           0.053309  0.788532         0.522000   
0              0.052632           0.121159  0.383499         0.724599   
0              0.200000           0.060171  0.952275         0.856582   
0              0.020000           0.025033  0.870603         0.514000   
0              0.100000           0.052946  0.928042         0.550000   

    worst_node.sd                              Dataset  
0        0.000204                  1067_kc1_5_1.csv.gz  
0        0.002257     825_boston_corrected_20_3.csv.gz  
0        0.000198  728_analcatdata_supreme_10_2.csv.gz  
0        0.006941               1012_flags_20_6.csv.gz  
0        0.123363            885_transplant_5_1.csv.gz  
..            ...                 

In [7]:
df = pd.read_csv('Results/NoisyDatasetsAfterFilters_GE-5_resultsKNN.csv.zip')
for i in df ['test_f1_macro']:
    print (i)

[0.63850055 0.62496297 0.64495192 0.64812007 0.66361158]
[0.45799595 0.61174026 0.39593301 0.59821525 0.66583954]
[0.79445041 0.52352817 0.98523368 0.99174229 0.38380846]
[0.59655172 0.43019481 0.47814451 0.62012987 0.59285714]
[0.76923077 1.         1.         1.         0.69047619]
[0.55222222 0.54453111 0.54494286 0.57632611 0.67047587]
[0.45054945 0.6969697  0.49494949 0.6969697  0.79166667]
[1.         0.98140083 0.79382367 0.92507097 0.76611514]
[0.79947062 0.77206502 0.9164017  0.78491895 0.88421782]
[0.86805556 0.97212032 0.88307692 0.93280283 0.809319  ]
[0.71264368 0.75961538 0.61616162 0.73480212 0.65656566]
[0.75824176 0.75824176 0.8021978  0.78549979 0.74533107]
[0.56597222 0.55286169 0.4550719  0.60435372 0.82371795]
[0.55218855 0.48821549 0.63461538 0.85098039 0.56783468]
[0.6        0.39393939 0.39393939 0.53125    0.78494624]
[0.55021797 0.58981183 0.57696254 0.56109896 0.53738893]
[0.89812403 0.69122807 0.84758786 0.89323451 0.7924036 ]
[0.51388889 0.89631336 0.676470

0.49348802999999997